### ISSUE TITLE
object has no method 'hasOwnProperty'

### ISSUE THREAD

**Issue by kuniwaa** [joelabair/multer-autoreap#11]
Here a part of package.json:
`"express": "^4.14.0",
    "multer": "^1.1.0",
    "multer-autoreap": "^0.1.0"`
And when I'm using autoreap, I'm getting this uncaught exception:
`Object object has no method 'hasOwnProperty' `

I have researched this error and I think it's because of multer using:
`Object.create(null);`
This will yield an object with a null prototype, which therefore does not inherit any methods.

Would not it be better to use:
`if (Object.prototype.hasOwnProperty.call(req.files, key) && !~done.indexOf(key)) {`
instead of:
`if (req.files.hasOwnProperty(key) && !~done.indexOf(key)) {`
on line 37?

**Comment by joelabair** [comment]
Or it's because req.files is null or an array.  Either way, this is new.

I haven't encountered this error previously.  What node version an platform are you on?

Your proposal looks like a good remedy.  Can you compose or append a unit test exposing the use case?  If so,  I'll gladly merge your pull request.
