### ISSUE TITLE
reaped on res.socket close event - is this correct?

### ISSUE THREAD

**Issue by martinsson** [joelabair/multer-autoreap#14]
What I was expecting: files are reaped on 'finished' event of the response object

What it does: reaps file also on response.socket object, close and error events

Why this is a problem: autoreap deletes files before I do res.send(). Interestingly I can only reproduce this with selenium tests. Somehow the socket is closed very early when I upload a file with selenium. I'm currently exploring whether the selenium server has some strange behavior when we do the following webdriver command: $(uploadForm).sendKeys()  

I see only one alternative to solve my problem
- propose a patch where I remove the term 'close' in the finish.js. Actually I'm ignorant as to why we listen on the socket at all, doesn't the 'finish' event on response always get fired?

Does that seem reasonable? If not on monday I'll try to produce a minimal example reproducing the problem.

Oh this is similar to #13 but not the same problem afaik

Cheers

**Comment by martinsson** [comment]
I mentioned this issue in the on-finished issues: https://github.com/jshttp/on-finished/issues/19

**Comment by martinsson** [comment]
I tried to fix it using another response-end-listener like express-end. 
https://github.com/martinsson/multer-autoreap/tree/fixFileReapedOnSocketCloseAlternative
https://github.com/martinsson/multer-autoreap/tree/fixFileReapedOnSocketClose

However that makes the error tests fail, as we're not transporting the error object to processFile().

Not sure how to fix this at all. Perhaps the addition i proposed to on-finished?

**Comment by joelabair** [comment]
Sorry you're having trouble, and I'm happy to help.
 
re:
> Actually I'm ignorant as to why we listen on the socket at all

To answer your initial post: node's HTTP api is a subclass of net.Socket.  This means that events on the response object are directly leveraging the interface exposed by net.socket.  _(keep in mind - this is not referring explicitly to webSocket internals, even though they would use as similar subsystem)_ net.Socket is a node core internal API.

As documented by the HTTP module here - http://devdocs.io/node~4_lts/http#http_class_http_server

> Class: http.Server

> Added in: v0.1.17
> This class inherits from net.Server and has the following additional events:

> Event: 'clientError'

> Added in: v0.1.94
> function (exception, socket) { }

> If a client connection emits an 'error' event, it will be forwarded here.

> socket is the net.Socket object that the error originated from.

If you'd like more information as to why a network socket is used to handle HTTP requests, the short answer is its related to the underlying TCP/IP network stack.

And regarding the **finished** API...

From the documentation here - https://github.com/jshttp/on-finished

> In Node.js, these request objects come from the 'connect' event on the HTTP server.

> When this module is used on a HTTP CONNECT request, the request is considered "finished" > immediately, due to limitations in the Node.js interface. This means if the CONNECT request contains a request entity, the request will be considered "finished" even before it has been read.

> There is no such thing as a response object to a CONNECT request in Node.js, so there is no support for for one.

**NOTE**
> When this module is used on a HTTP request with an Upgrade header, the request is considered "finished" immediately, due to limitations in the Node.js interface. This means if the Upgrade request contains a request entity, the request will be considered "finished" even before it has been read.

Based on this documentation, the first thing to eliminate is that selenium is not performing an UPGRADE request.  I can update the release to include the latest version of on-finished, but that may not alleviate any issue you;re having.  

This is impossible for me to debug without some demonstrable code illustration. The problem appears to originate from your selenium test behaving in an unexpected way.  And writing a small reproducible unit test  will help to flesh out the source of the issue.  Unfortunately, it seems like you may be attempting to fix the wrong end of the issue here.  nonetheless... 

1. can you dump the express HTTP headers and BODY of the request that triggers the issue?
2. using this information reproduce the error outside of selenium.
3. write a minimal dependencies test illustration demonstrating the issue.

**Comment by martinsson** [comment]
Thanks for your interest. 

req.headers and req.body are identical between manual browsing and selenium unfortunately

I'll need some time to reproduce this with a minimal stack. Attempts so far are unsuccessful in reproducing the issue.
